# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('department', models.CharField(max_length=80)),
                ('start_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('speciality', models.CharField(max_length=80)),
                ('birth_day', models.DateField()),
                ('country', models.CharField(max_length=80)),
            ],
        ),
    ]
