# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-21 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_cours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Course',
        ),
    ]
